<?php
/**
 * @file
 * Code for the Feature Core feature.
 */

include_once 'feature_core.features.inc';

/**
 * Implements hook_menu_alter().
 * Thanks to pfournier, creator of module Empty Front Page (https://www.drupal.org/project/empty_front_page)
 */
function feature_core_menu_alter(&$items) {
	$items['node']['page callback'] = 'empty_front_page_callback';
}

function empty_front_page_callback() {
	drupal_set_title('');
	return array();
}

/**
 * Implements hook_block_info().
 */
function feature_core_block_info() {
	$blocks = array();

	$blocks['rouergue_copyright'] = array(
			'info' => t('Rouergue Copyright'),
			'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function feature_core_block_view($delta = '') {
	switch ($delta) {
		case 'rouergue_copyright':
			$block['subject'] = '';
			$variables['copyright-text'] = 'Éditions du Rouergue';
			$block['content'] = theme('rouergue_copyright', $variables);
			return $block;
			break;
	}
}

/**
 * Implements hook_theme().
 */
function feature_core_theme() {
	return array(
			'rouergue_copyright' => array(
					'variables' => array('copyright-text' => NULL),
					'file' => 'feature_core.theme.inc',
			),
	);
}