<?php

/**
 * @file
 * Display Suite rouergue_12_stacked configuration.
 */

function ds_rouergue_12_stacked() {
  return array(
    'label' => t('rouergue_12_stacked'),
    'regions' => array(
      'top' => t('Top'),
      'middle' => t('Middle'),
    ),
    // Uncomment if you want to include a CSS file for this layout (rouergue_12_stacked.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (rouergue_12_stacked.png)
    // 'image' => TRUE,
  );
}
