<?php
/**
 * @file
 * Code for the Migrate Mistral module.
 */

/**
 * Implements hook_permission().
 */
function migrate_mistral_permission() {
	return array(
		'administer mistral' => array(
				'title' => t('Administer Mistral'),
				'description' => t('Allows to handle various Mistral imports'),
		),
	);
}

/**
 * Implements hook_menu().
 */
function migrate_mistral_menu() {
	$items = array();
	
	$items['mistral_import'] = array(
			'title' => 'Mistral import',
			'description' => 'Launches Mistral data import from local mistral database.',
			'page callback' => 'rouergue_mistral_import',
			'access arguments' => array('administer mistral'),
			'type' => MENU_CALLBACK,
	);	
	$items['mistral_synchronize'] = array(
			'title' => 'Mistral Synchronization',
			'description' => 'Launches Mistral local database regeneration import from Mistral dump archive, followed by data import.',
			'page callback' => 'rouergue_mistral_synchronize',
			'access arguments' => array('administer mistral'),
			'type' => MENU_CALLBACK,
	);
	
	return $items;
}

/**
 * Implements hook_cron()
 */
function migrate_mistral_cron() {
	rouergue_mistral_synchronize();
}

/**
 * Callback functions.
 */

function rouergue_mistral_import() {
	return _mistral_import();
}

function rouergue_mistral_synchronize() {
	$day = variable_get('rouergue_mistral_sync_day');
	$current_day = date('N');
	
	if ($current_day != $day) {
		return "Nothing to do today.";
	}
	else {
		$filepath = variable_get('rouergue_mistral_dumps_directory');
		$filename = variable_get('rouergue_mistral_dump_filename');
		$dumpfile = $filepath . $filename;
		
		if (!file_exists($dumpfile)) {
			$msg = t('The dump file %file does not exist in folder %folder', array('%$file' => $filename, '%folder' => $filepath));
			watchdog('mistral', $msg);
			
			return "Synchronization process failed.<br /><b>$filename</b> not found in <b>$filepath</b>.";			
		}
		else {
			$drush = variable_get('rouergue_drush_path');
			$drop_cmd = "$drush sql-drop --database=mistral -y";
			$insert_cmd = "$drush sql-query --database=mistral --file=$dumpfile";
			
			// Mistral local database regeneration
			shell_exec($drop_cmd);
			shell_exec($insert_cmd);
			
			$msg = t('Synchronization done on %date', array('%date' => date('d/m/Y - H:i:s')));
			watchdog('mistral', $msg);
			$return_msg = "Synchronization process completed.";
			
			// Mistral data update into Drupal database (existing data are updated, new data are imported).
			$return_msg .= "<br />" . _mistral_import();
			
			return $return_msg;
		}
	}
}

function _mistral_import() {
	$migrations = array('theme','readership','article','function','contributor','articleContributors');
	foreach ($migrations as $key) {
		$migration = Migration::getInstance($key);
		$migration->prepareUpdate();
		$result = $migration->processImport();
		$msg = t('%mistral_data import result : %result', array('%mistral_data' => strtoupper($key), '%result' => $result));
		watchdog('mistral', $msg);
	}
	
	return "Mistral data update completed.";
}

