<?php

/**
 * @file
 * Display Suite rouergue_4_5_3 configuration.
 */

function ds_rouergue_4_5_3() {
  return array(
    'label' => t('rouergue_4_5_3'),
    'regions' => array(
      'top' => t('Top'),
      'left' => t('Left'),
      'middle' => t('Middle'),
      'right' => t('Right'),
    ),
    // Uncomment if you want to include a CSS file for this layout (rouergue_4_5_3.css)
    // 'css' => TRUE,
    // Uncomment if you want to include a preview for this layout (rouergue_4_5_3.png)
    // 'image' => TRUE,
  );
}
