<?php
/**
 * @file
 * Main section for the Resave Nodes module.
 *
 * This module will resave nodes of selected content types based on various
 * rules (created/updated since last time cron was run, or just all nodes
 * regardless of create/update time) at configured times (via cron or
 * multiple times of day).  This will force computed fields to be computed
 * (geolocation, media players, etc.).
 */

require_once drupal_get_path('module', 'resave_nodes') . '/inc/resave_nodes.form_admin.inc';
require_once drupal_get_path('module', 'resave_nodes') . '/inc/resave_nodes.func_general.inc';


/**
 * Implements hook_help().
 */
function resave_nodes_help($path, $arg) {
  if ($path == 'admin/help#resave_nodes') {
    return t('<p>The Resave Nodes module allows for the automatic resaving of
      nodes.  The resaving of nodes can be handled automatically through
      Drupal\'s cron functionality or it can be managed with a Unix-style cron
      configuration. The nodes that are resaved can be either the ones that have
      been created or changed since the last time the module ran (via one of the
      two cron options) or it can be all nodes regardless of created/change
      date.  It can also be restricted to nodes of selected content types.</p>
      <p>If the Unix-style cron is required, be sure to set cron to run every
      1 hour under \'Configuration > System > Cron\'.</p>');
  }
}


/**
 * Implements hook_menu().
 */
function resave_nodes_menu() {
  $items['admin/config/system/resave_nodes'] = array(
    'title'            => 'Resave Nodes',
    'description'      => t('Configure the content types and frequency for resaving nodes.'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('resave_nodes_form'),
    'access arguments' => array('administer node resaving'),
    'type'             => MENU_NORMAL_ITEM,
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function resave_nodes_permission() {
  return array(
    'administer node resaving' => array(
      'title' => t('Administer the content types and frequency for resaving nodes.'),
    ),
  );
}


/**
 * Implements hook_cron().
 */
function resave_nodes_cron() {
  $resave_nodes_scheduling = variable_get('resave_nodes_use_cron');

  if ($resave_nodes_scheduling == 'run_with_cron') {
    resave_nodes_do_that_thing();
  }
}


/**
 * Implements hook_cron_job_scheduler_info().
 */
function resave_nodes_cron_job_scheduler_info() {
  $info = array();
  $info['resave_nodes_do_that_thing'] = array(
    'worker callback' => 'resave_nodes_do_that_thing',
  );
  return $info;
}
