<?php
/**
 * @file
 * Code for the Feature Workshops feature.
 */

include_once 'feature_workshops.features.inc';

/**
 * Implements hook_block_info().
 */
function feature_workshops_block_info() {
	$blocks = array();

	$blocks['rouergue_workshops_browse_buttom'] = array(
			'info' => t('Rouergue Browse button'),
			'cache' => DRUPAL_NO_CACHE,
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function feature_workshops_block_view($delta = '') {
	switch ($delta) {
		case 'rouergue_workshops_browse_buttom':
			$block['subject'] = '';
			$content = '';
			$node = menu_get_object();
			// The block will contain button's HTML code only if the node being viewed has inner pages pdf file attached.
			if (!empty($node->field_inner_pages)) {
				$content = '<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#rouergue-pdf-viewer">Feuilleter</button>';
			}
			$block['content'] = $content;
			return $block;
			break;
	}
}

/**
 * Implements hook_block_view_alter().
 */
function feature_workshops_block_view_alter(&$data, $block) {
	if ($block->delta == 'workshops-workshop_media_block') {
		if (!strstr($data['content']['#markup'], 'views-field-field-video') && !strstr($data['content']['#markup'], 'views-field-field-sound')) {
			$data['subject'] = '';
		}
	}
}